set eprj_proj_name "zturn_axi4s2dma_demo"
set eprj_def_root "src"
set eprj_top_entity "design_1_wrapper"
set eprj_board_part ""
set eprj_part "xc7z020clg400-1"
set eprj_target_language "VHDL"
set eprj_simulator_language "Mixed"
set eprj_default_lib "xil_defaultlib"
set eprj_synth_flow "Vivado Synthesis 2017"
set eprj_synth_strategy "Flow_PerfOptimized_high"
set eprj_impl_flow "Vivado Implementation 2017"
set eprj_impl_strategy "Performance_Retiming"
set eprj_vivado_version "2017.4"
set eprj_vivado_version_allow_upgrade false

